version: '3'

volumes:
  db_data:

services:
  app:
    build: .
    image: reuters_parsing
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - WAIT_HOSTS=${POSTGRES_HOST}:${POSTGRES_PORT}
      - PYTHONPATH=/srv/
    working_dir: /srv/output
    volumes:
      - .:/srv/output
    command: /bin/bash -c "
      waitc &&
      python3.8 -m reuters_parsing ${APP_ACTION:-} ${APP_PARAM:-}
      "

  postgres:
    image: postgres:11.5
    tty: true
    restart: always
    env_file:
      - ./.env
    volumes:
        - db_data:/var/lib/postgresql/data

